name: "Terraform Push Pipeline"
on:
  push:
    branches:
      - main
      
jobs:
  build-aws-infra:
    name: "Terraform CI/CD"
    runs-on: ubuntu-22.04
     
    # Set environment variables for cloud credentials using GitHub Secrets
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-1

    steps:
      # 1. Fetch the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Check Terraform version
      - name: Setup Terraform
        run: terraform version

      # 3. Check for proper code formatting syntax
      - name: Terraform Format Check
        run: terraform fmt

      # 4. Download providers and initialize backend state
      - name: Terraform Init
        run: terraform init

      # 5. Validate the configuration files
      - name: Terraform Validate
        run: terraform validate

      # 6. Generate speculative execution plan on Pull Requests
      - name: Terraform Plan
        run: terraform plan

      # 7. Automatically execute changes ONLY on direct push/merge to main branch
      - name: Terraform Apply
        run: terraform apply -auto-approve

